### ISSUE TITLE
A README.md would be helpful

### ISSUE THREAD

**Issue by zoechi** [dart-lang/code-transformers#2]
I have no idea what this package is supposed to do.

**Comment by jakemac53** [comment]
Good point :), this has been kind of a dumping ground for a while for shared logic relating to creating and testing transformers.

**Comment by jakemac53** [comment]
Alright, I got at least a good start on this. There are sections with TODO's for further documentation but at least you can get an idea of the general things this package does.

**Comment by zoechi** [comment]
Already helpful :+1: :-)
